# Generated by Django 5.0.4 on 2024-05-23 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timeperiod', models.CharField(max_length=5)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('exposure_time_percent', models.FloatField()),
                ('equity_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_peak', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_percent', models.FloatField()),
                ('annual_return_percent', models.FloatField()),
                ('max_drawdown_percent', models.FloatField(blank=True, null=True)),
                ('sharpe_ratio', models.FloatField()),
                ('sortino_ratio', models.FloatField()),
                ('calmar_ratio', models.FloatField(blank=True, null=True)),
                ('number_of_trades', models.IntegerField()),
                ('win_rate_percent', models.FloatField()),
                ('avg_trade_percent', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('sqn', models.FloatField(blank=True, null=True)),
                ('graph_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backtest',
                'verbose_name_plural': 'Backtests',
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Optimize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timeperiod', models.CharField(max_length=5)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('atr_timeperiod', models.DecimalField(decimal_places=2, max_digits=5)),
                ('atr_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sharpe_ratio', models.FloatField()),
                ('return_percent', models.FloatField()),
                ('max_drawdown_percent', models.FloatField()),
                ('graph_link', models.URLField(blank=True, null=True)),
                ('heat_map_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('exposure_time_percent', models.FloatField()),
                ('equity_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_peak', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_return_percent', models.FloatField()),
                ('number_of_trades', models.IntegerField()),
                ('win_rate_percent', models.FloatField()),
                ('avg_trade_percent', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('sortino_ratio', models.FloatField()),
                ('calmar_ratio', models.FloatField()),
                ('sqn', models.FloatField(blank=True, null=True)),
                ('repetitions', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Optimization',
                'verbose_name_plural': 'Optimizations',
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
