# Generated by Django 5.0.4 on 2024-04-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('result_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Backtest',
                'verbose_name_plural': 'Backtests',
            },
        ),
        migrations.CreateModel(
            name='Optimize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('timeperiod', models.CharField(max_length=255)),
                ('repetitions', models.IntegerField()),
                ('atr_timeperiod', models.FloatField()),
                ('atr_multiplier', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Optimize',
                'verbose_name_plural': 'Optimizes',
            },
        ),
    ]
