# Generated by Django 5.0.4 on 2024-04-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('exposure_time_percent', models.FloatField()),
                ('equity_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_peak', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_percent', models.FloatField()),
                ('annual_return_percent', models.FloatField()),
                ('max_drawdown_percent', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('sortino_ratio', models.FloatField()),
                ('calmar_ratio', models.FloatField()),
                ('number_of_trades', models.IntegerField()),
                ('win_rate_percent', models.FloatField()),
                ('avg_trade_percent', models.FloatField()),
                ('profit_factor', models.FloatField()),
                ('sqn', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backtest',
                'verbose_name_plural': 'Backtests',
            },
        ),
        migrations.DeleteModel(
            name='Backtests',
        ),
    ]
