# Generated by Django 5.0.4 on 2024-05-25 22:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_alter_coin_symbol'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='timeperiod',
        ),
        migrations.RemoveField(
            model_name='optimize',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='optimize',
            name='timeperiod',
        ),
        migrations.AddField(
            model_name='backtest',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='openbrowser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backtest',
            name='timeframe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='optimize',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange'),
        ),
        migrations.AddField(
            model_name='optimize',
            name='max_tries',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='optimize',
            name='openbrowser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='optimize',
            name='timeframe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='annual_return_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='equity_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='equity_peak',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='exposure_time_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='number_of_trades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='return_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='sharpe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='sortino_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 25, 22, 39, 40, 727132, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='win_rate_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='annual_return_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='atr_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='atr_timeperiod',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='calmar_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='equity_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='equity_peak',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='exposure_time_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='max_drawdown_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='number_of_trades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='return_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='sharpe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='sortino_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 25, 22, 39, 40, 728206, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='win_rate_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='papertrade',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
