# Generated by Django 5.0.4 on 2024-04-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_backtest_cash_backtest_commission_backtest_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='graph_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
