# Generated by Django 5.0.4 on 2024-04-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_backtest_graph_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='timeperiod',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backtest',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
