# Generated by Django 5.0.4 on 2024-04-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_optimize_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimize',
            name='annual_return_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='atr_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='atr_timeperiod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='avg_trade_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='equity_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='equity_peak',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='exposure_time_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='max_drawdown_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='number_of_trades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='profit_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='return_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='sharpe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='win_rate_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
