# Generated by Django 5.0.4 on 2024-04-12 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_optimize_annual_return_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimize',
            name='calmar_ratio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimize',
            name='sortino_ratio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='annual_return_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='atr_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='atr_timeperiod',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='avg_trade_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 11, 50, 9, 410060, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='equity_final',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='equity_peak',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='exposure_time_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='max_drawdown_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='number_of_trades',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='profit_factor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='return_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='sharpe_ratio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimize',
            name='win_rate_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
