# Generated by Django 5.0.4 on 2024-04-12 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_optimize_calmar_ratio_optimize_sortino_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimize',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='profit_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='sqn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
