# Generated by Django 5.0.4 on 2024-04-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_optimize_end_date_alter_optimize_profit_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimize',
            name='heat_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
