# Generated by Django 5.0.4 on 2024-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_optimize_heat_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimize',
            name='atr_timeperiod',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
