# Generated by Django 5.0.4 on 2024-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_optimize_atr_timeperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='calmar_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='max_drawdown_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='profit_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='sqn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
