# Generated by Django 5.0.4 on 2024-04-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_backtest_calmar_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='avg_trade_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimize',
            name='avg_trade_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
