# Generated by Django 5.0.4 on 2024-04-15 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_backtest_avg_trade_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimize',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
